version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=your-jwt-secret-here
      - DATABASE_URL=postgresql://postgres:password@db:5432/vectorify_db
      - GEMINI_API_KEY=your-groq-key-here
      - RESEND_API_KEY=your-resend-key-here
      - REDIS_URL=redis://redis:6379
      - REMINDER_CRON_SCHEDULE=*/5 * * * *
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vectorify_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
